name: Release
on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: version
        id: version
        run: |
          tag="${{ github.event.release.tag_name }}"
          version="${tag#v}"
          echo "tag=${tag}" >> $GITHUB_OUTPUT
          echo "version=${version}" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install qtbase5-dev qttools5-dev-tools
          sudo pip install qgis-plugin-ci --break-system-packages
      - name: Release
        run: |
          qgis-plugin-ci release ${{ steps.version.outputs.version }} \
              --release-tag ${{ steps.version.outputs.tag }} \
              --disable-submodule-update \
              --github-token ${{ secrets.GITHUB_TOKEN }} \
              --create-plugin-repo
